PropertyConstants = {
  PROPERTIES_RECEIVED: "PROPERTIES_RECEIVED",
	PROPERTY_RECEIVED: "PROPERTY_RECEIVED",
  FOCUSED_PROPERTY: "FOCUSED_PROPERTY",
  SEARCH_RECEIVED: "SEARCH_RECEIVED"
};

module.exports = PropertyConstants;
